apiVersion: paas.internal/v1
kind: Application
metadata:
  name: diseases-map
spec:
  image: ghcr.io/phumitada/diseases-map:37424c9-1789886010178
  port: 8080
  imagePullSecret: ghcr-secret
  databaseRef: []
  domain: diseases-map.phumitada.com
  envSecretRefs:
    - diseases-map-env-secret
