apiVersion: paas.internal/v1
kind: Application
metadata:
  name: diseases-map-api
spec:
  image: ghcr.io/phumitada/diseases-map-api:37424c9-1789884156667
  port: 5207
  imagePullSecret: ghcr-secret
  databaseRef: []
  domain: diseases-map-api.phumitada.com
  envSecretRefs:
    - diseases-map-api-env-secret
