apiVersion: paas.internal/v1
kind: Application
metadata:
  name: hotel-app
spec:
  image: ghcr.io/phumitada/hotel-app:ecc73bb
  port: 80
  imagePullSecret: ghcr-secret
  databaseRef: []
  domain: hotel.phumitada.com
  envSecretRefs:
    - hotel-app-env-secret
