apiVersion: paas.internal/v1
kind: Application
metadata:
  name: order-app
spec:
  image: ghcr.io/phumitada/order-app:293b405-1789961377874
  port: 8080
  imagePullSecret: ghcr-secret
  databaseRef: []
  domain: order-app.phumitada.com
  envSecretRefs:
    - order-app-env-secret
