apiVersion: paas.internal/v1
kind: Application
metadata:
  name: order-app
spec:
  image: ghcr.io/phumitada/order-app:b2caff3
  port: 55116
  imagePullSecret: ghcr-secret
  databaseRef: []
  domain: order-system.phumitada.com
  envSecretRefs:
    - order-app-env-secret
