apiVersion: paas.internal/v1
kind: Application
metadata:
  name: order-api
spec:
  image: ghcr.io/phumitada/order-api:b2caff3
  port: 55110
  imagePullSecret: ghcr-secret
  databaseRef:
    - order-api-postgres
    - order-api-redis
  envSecretRefs:
    - order-api-env-secret
