apiVersion: paas.internal/v1
kind: Application
metadata:
  name: order-api
spec:
  image: ghcr.io/phumitada/order-api:6780c9c-1789961603165
  port: 5001
  imagePullSecret: ghcr-secret
  databaseRef:
    - order-api-redis
    - order-api-postgres
  domain: order-app-api.phumitada.com
  envSecretRefs:
    - order-api-env-secret
